### ISSUE TITLE
No fixed ordering for swimlanes

### ISSUE THREAD

**Issue by mdpye** [vivangkumar/icanhazissues#10]
It's a bit confusing that they jump around - and kind of sort is fine as long as it's stable...

**Comment by vivangkumar** [comment]
I know what the issue is. When I render the swim lanes, I use a `for in` loop. And that does not guarantee ordering when iterating through a list. Should be a minor fix.

**Comment by vivangkumar** [comment]
Well, as much as I like jade as a templating language, it is quite limiting. I'll just use plain ol JS.

**Comment by vivangkumar** [comment]
Fixed as of ec9b12a75526d5ccfe9c61b3a5f5615ee5ef622e
