### ISSUE TITLE
Space improvement

### ISSUE THREAD

**Issue by zimbatm** [vivangkumar/icanhazissues#18]
We could gain some vertical space by making the avatar overlap the issue.

Currently:
![current](https://cloud.githubusercontent.com/assets/3248/7101606/efa81da8-e058-11e4-8550-8ee0bfed16fb.png)

Overlapping:
![collapsed](https://cloud.githubusercontent.com/assets/3248/7101604/ec3150b8-e058-11e4-8323-f60acd641061.png)

**Comment by vivangkumar** [comment]
True. This is next on my list. ;)

**Comment by vivangkumar** [comment]
Had a thought about this. This is fine for one line cards. What about when there are multiple lines? The container would be big enough to accommodate the picture itself.

**Comment by zimbatm** [comment]
The trick is to vertically align the avatar. If there's multiple lines the avatar would thus appear to be inside of the card.

**Comment by zimbatm** [comment]
No relevant anymore
