### ISSUE TITLE
Make the cards stand out from the background better

### ISSUE THREAD

**Issue by maxthelion** [vivangkumar/icanhazissues#26]
At the moment, the cards are a bit too similar to the grey boxes they sit in. This makes it quite tricky to see where the cards are from a quick glance. Maybe the drop targets could just have outlines, rather than being solid colour (as shown in image). Otherwise, potentially make them a darker colour, or more similar to the background.

![image](https://cloud.githubusercontent.com/assets/999/7226738/436ff0d2-e743-11e4-95c0-9b213664105b.png)

**Comment by vivangkumar** [comment]
Fair enough. Colour suggestions welcome :P

**Comment by maxthelion** [comment]
#215963

**Comment by vivangkumar** [comment]
https://github.com/vivangkumar/icanhazissues/pull/28 addressed this
