### ISSUE TITLE
Action to close "done" items

### ISSUE THREAD

**Issue by zimbatm** [vivangkumar/icanhazissues#30]
After a retrospective we want to quickly close all the issues in the "done" column. Right now we have to open and close all the issues one by one.

**Comment by vivangkumar** [comment]
Sure. I have enough things to work on over the weekend now ;)

**Comment by vivangkumar** [comment]
Added a button to close all items at once, that are in the done column. 014d66e5601fba6cc0762f9651cdcfb4e4be6653 addressed this
