### ISSUE TITLE
Redundant comment

### ISSUE THREAD

**Issue by zimbatm** [vivangkumar/icanhazissues#33]
It's not necessary to post a comment when the tags already indicate what's happening:
![screen shot 2015-05-07 at 18 19 58](https://cloud.githubusercontent.com/assets/3248/7521431/b4a55e18-f4e5-11e4-82e2-d81392e35d26.png)

**Comment by vivangkumar** [comment]
I replicated the current functionality. I think the reason behind commenting was that it appears on the notifications page. Changing the labels does not show on the home page. Can be removed if needed. Not so sure how Max would feel about it :P

**Comment by zimbatm** [comment]
We can bring that up to a vote. Personally I'm more interested in code and
some human comments and already have enough notifications as is.

**Comment by vivangkumar** [comment]
Haha. Sure. We can definitely vote on that. I have added review notifications so it should be better. Since we are mostly concerned when someone moves a card to review.

**Comment by zimbatm** [comment]
:+1:

**Comment by zimbatm** [comment]
We had another chat about it yesterday with @mdpie and @rumblesan and we agreed that the notifications are superfluous now that github shows the tag changes in the ticket.
