### ISSUE TITLE
Backlog column

### ISSUE THREAD

**Issue by zimbatm** [vivangkumar/icanhazissues#35]
When searching for new issues to pull from the backlog we basically have to go on github and search for issues that don't have a tag. It would be nice to have a toggle to load them in a column on the left, ordered by milestone.

**Comment by vivangkumar** [comment]
I was thinking about this today in fact. I could make it automatically pull some issues if the number of issues goes below a certain number. How does that sound?

**Comment by zimbatm** [comment]
How do you determine what issue to pull ? I think the backlog would have to be ordered for that to work.
