### ISSUE TITLE
Feature parity

### ISSUE THREAD

**Issue by zimbatm** [vivangkumar/icanhazissues#9]
Before switching to the new kanban board we want feature-parity with the existing one. This issue is a place-holder for that list of missing features:

* [x] More compact layout so it fits on a single page
* [x] Issues labelled as "blocked" have an indicator
* [x] Ageing; issues decay over time when they don't get any updates
* [x] Sends activity to eventinator (used by the gaggle report)

Bonus:
* [x] Reminders from the retrospective

**Comment by vivangkumar** [comment]
@zimbatm I think I know a way we can have the retrospective reminders without having to use a backend. Maybe we can leverage the html5 storage option and pull data from there. We could then use pusher to sync the data every time it changes and update values for every new client that connects.

**Comment by zimbatm** [comment]
PusherSync depends on both pusher and a backend for the fallback. Remember, the data is only kept inside of the event buffer for 5 minutes

**Comment by vivangkumar** [comment]
Not using pusher sync. Just using the standard pusher library using client events? Maybe what I'm not translating it into words properly enough. I'll try out what I have in my head today ;)

**Comment by zimbatm** [comment]
It would work but only if at least one client that has the data and is online (to transmit to the other one).

Another solution would be to add a "retrospective" tag to issues.

**Comment by vivangkumar** [comment]
^ Yup. I had a think about it and realised that. Someone needs to be online. What would be the point of adding the 'retrospective' tag? We need reminders right? That means we have to create an issue with the title of what the reminder has to be.

**Comment by zimbatm** [comment]
You know when we use the keep/improve/stop/start columns to put up some cards during retrospective ?Some of these items are actions, these just need to be transformed into issues and assigned accordingly. But some of those are behavioural things like "be more careful with the deploys", they don't really fit in the kanban model.

The issue right now (at least for me) is that I tend to forget about these retrospective items quite quickly, that's why I think it would make sense to put them up in some form in the kanban board, just to remind us about them. Because they're not actionable they can never be done. As as start could instead put up an arbitrary limit (let's say 3) and replace these items.

**Comment by vivangkumar** [comment]
It should not take up a lot of space. Just that we need to assign a new label to these items. I also dont want to use a database just to store three items.

**Comment by maxthelion** [comment]
The retrospective items shouldn't be mixed up with the Kanban board. It's already pressed for space.  I think we should display the retrospective items on a separate page, that would be part of the slideshow on the dashboard TV.

**Comment by vivangkumar** [comment]
I agree with that ^ It does seem like a better idea. I can create a new route to /retrospective-reminders that goes to the page.

**Comment by zimbatm** [comment]
The kanban board is the only space I look frequently at. Would a single line of text make a big difference ?

**Comment by vivangkumar** [comment]
Well, if its merely a line of text with three reminders spaced properly, maybe. I'll deploy a version today (hopefully) We'll see how that works out.

**Comment by vivangkumar** [comment]
Right. Ive added in support for retrospective reminders in the `retrospective-reminders` branch. We can add a maximum of 5 reminders if you want it on the same page so that the board looks nice. We could add more if we move this a separate page. 

Let me know if you like this format, or I'll move it to a new page like max said.
![screen shot 2015-04-11 at 1 55 54 pm](https://cloud.githubusercontent.com/assets/6005628/7101456/87cca998-e052-11e4-9dad-bb735a64b496.png)

**Comment by zimbatm** [comment]
This is great ! Let's see if the other users of the board are happy with it
too.

**Comment by maxthelion** [comment]
Putting the retro items in columns creates a strange association UX-wise. I'd probably put them above the column headers, and avoid tying them to the column widths.

**Comment by vivangkumar** [comment]
I made it more into a bullet format

![image](https://cloud.githubusercontent.com/assets/6005628/7120409/ebde40c8-e204-11e4-93ba-b1a83d01cbff.png)

**Comment by vivangkumar** [comment]
Closing this because the remaining space constraint feature is another issue on the repository
